# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gapi_app', '0002_calendar_calendarevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='calendar_id',
            new_name='calendar',
        ),
    ]
